name: CI
on:
  push:
    branches:
      - master

jobs:
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter create .
      - run: flutter pub get
      - run: dart run flutter_launcher_icons
      - run: flutter --version
      - name: "Setting up android"
        run: |
          sh setup_android.sh
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          UPLOAD_KEYSTORE_JKS: ${{ secrets.UPLOAD_KEYSTORE_JKS }}
      #     - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
      #     - run: flutter build appbundle --target-platform android-arm,android-arm64
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/apk/release
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/app-release.apk
  # build_ios:
  #   name: Build Flutter (iOS)
  #   runs-on: macOS-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: '17'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         flutter-version: 3.19.4
  #     - run: flutter pub get
  #     - run: flutter clean
  #     - run: flutter build ios --release --no-codesign
  #     - run: mkdir -p Payload
  #     - run: mv ./build/ios/iphoneos/Runner.app Payload
  #     - run: zip -r -y Payload.zip Payload/Runner.app
  #     - run: mv Payload.zip Payload.ipa
  #     - name: Upload iPA
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: ios-build
  #         path: Payload.ipa
